# Generated by Django 4.2.7 on 2025-04-06 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Diretoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('membros', models.ManyToManyField(related_name='diretorias', to=settings.AUTH_USER_MODEL, verbose_name='Membros')),
            ],
            options={
                'verbose_name': 'Diretoria',
                'verbose_name_plural': 'Diretorias',
                'ordering': ['nome'],
            },
        ),
    ]
