# Generated by Django 4.2.7 on 2025-04-06 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('okrs', '0002_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do Objetivo')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='okrs.time', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
                'ordering': ['-ano', 'time'],
            },
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição do Key Result')),
                ('tipo_valor', models.CharField(choices=[('INT', 'Número Inteiro'), ('PORC', 'Porcentagem'), ('MOEDA', 'Valor em Reais')], default='INT', max_length=5, verbose_name='Tipo de Valor')),
                ('valor_target', models.DecimalField(decimal_places=2, help_text='Valor alvo a ser atingido', max_digits=15, verbose_name='Valor Target')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='okrs.objetivo', verbose_name='Objetivo')),
            ],
            options={
                'verbose_name': 'Key Result',
                'verbose_name_plural': 'Key Results',
                'ordering': ['objetivo', 'descricao'],
            },
        ),
        migrations.CreateModel(
            name='KeyResultProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('1', '1º Trimestre'), ('2', '2º Trimestre'), ('3', '3º Trimestre'), ('4', '4º Trimestre')], max_length=1, verbose_name='Trimestre')),
                ('valor_atual', models.DecimalField(decimal_places=2, help_text='Valor atual do progresso', max_digits=15, verbose_name='Valor Atual')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('key_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='okrs.keyresult', verbose_name='Key Result')),
            ],
            options={
                'verbose_name': 'Progresso do Key Result',
                'verbose_name_plural': 'Progressos dos Key Results',
                'ordering': ['key_result', 'trimestre'],
                'unique_together': {('key_result', 'trimestre')},
            },
        ),
    ]
