# Generated by Django 4.2.7 on 2025-04-07 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0003_objetivo_keyresult_keyresultprogresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresultprogresso',
            name='diretoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='okrs.diretoria', verbose_name='Diretoria'),
        ),
    ]
