# Generated by Django 4.2.7 on 2025-04-08 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0004_keyresultprogresso_diretoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyresultprogresso',
            name='data_progresso',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data em que o progresso foi registrado', verbose_name='Data do Progresso'),
        ),
    ]
