# Generated by Django 4.2.7 on 2025-04-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0006_kpi_kpiprogresso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['-relevancia', 'nome'], 'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='diretoria',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='time',
        ),
        migrations.AddField(
            model_name='kpi',
            name='formula_calculo',
            field=models.TextField(default=0, help_text='Descreva a fórmula ou método de cálculo deste KPI', verbose_name='Fórmula de Cálculo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi',
            name='relevancia',
            field=models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Média'), ('BAIXA', 'Baixa')], default='MEDIA', max_length=5, verbose_name='Relevância'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome do KPI'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='tipo_valor',
            field=models.CharField(choices=[('NUMERO', 'Número'), ('PORCENTAGEM', 'Porcentagem'), ('MOEDA', 'Moeda')], default='NUMERO', max_length=20, verbose_name='Tipo de Valor'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='valor_target',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Target'),
        ),
    ]
