# Generated by Django 4.2.7 on 2025-04-16 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('okrs', '0007_alter_kpi_options_remove_kpi_diretoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('custo_planejado', models.DecimalField(decimal_places=2, help_text='Custo total planejado para o projeto', max_digits=15, verbose_name='Custo Planejado')),
                ('receita_planejada', models.DecimalField(decimal_places=2, help_text='Receita total planejada para o projeto', max_digits=15, verbose_name='Receita Planejada')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('diretoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='okrs.diretoria', verbose_name='Diretoria Responsável')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='ProjetoProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Progresso')),
                ('custo_realizado', models.DecimalField(decimal_places=2, help_text='Custo realizado até a data', max_digits=15, verbose_name='Custo Realizado')),
                ('receita_realizada', models.DecimalField(decimal_places=2, help_text='Receita realizada até a data', max_digits=15, verbose_name='Receita Realizada')),
                ('farol', models.CharField(choices=[('CRITICO', 'Crítico'), ('ATRASADO', 'Atrasado'), ('EM_DIA', 'Em Dia'), ('ATENCAO', 'Atenção'), ('PAUSADO', 'Pausado'), ('CONCLUIDO', 'Concluído'), ('ENTREGUE', 'Entregue')], max_length=10, verbose_name='Status do Projeto')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('atualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressos', to='okrs.projeto', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Progresso do Projeto',
                'verbose_name_plural': 'Progressos dos Projetos',
                'ordering': ['-data'],
            },
        ),
    ]
