# Generated by Django 4.2.7 on 2025-04-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0008_projeto_projetoprogresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoprogresso',
            name='plano_acao',
            field=models.TextField(blank=True, help_text='Plano de ação necessário quando o farol está crítico, atrasado ou em atenção, ou quando o custo realizado excede o planejado', null=True, verbose_name='Plano de Ação'),
        ),
    ]
