# Generated by Django 4.2.7 on 2025-04-16 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0009_projetoprogresso_plano_acao'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoprogresso',
            name='diretoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='okrs.diretoria', verbose_name='Diretoria'),
            preserve_default=False,
        ),
    ]
