# Generated by Django 4.2.7 on 2025-04-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrs', '0010_projetoprogresso_diretoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cliente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Cliente'),
        ),
    ]
